### ISSUE TITLE
Potential Bug: Null Validator Address Array

### ISSUE THREAD

**Issue by forgxyz** [FlipsideCrypto/terra-models#76]
Latest tests are alerting with the following

```
08:12:46  Completed with 1 error and 2 warnings:
08:12:46  
08:12:46  Failure in test not_null_core__fact_blocks_VALIDATOR_ADDRESS_ARRAY (models/core/core__fact_blocks.yml)
08:12:46    Got 1176 results, configured to fail if != 0
08:12:46  
08:12:46    compiled SQL at target/compiled/terra/models/core/core__fact_blocks.yml/not_null_core__fact_blocks_VALIDATOR_ADDRESS_ARRAY.sql
08:12:46  
08:12:46    See test failures:
  ---------------------------------------------------------------------
  select * from TERRA.not_null_core.fact_blocks_VALIDATOR_ADDRESS_ARRAY
  ---------------------------------------------------------------------
```

**Comment by D0R11** [comment]
Checking this one out.

**Comment by antonyip** [comment]
https://flipsidecrypto.xyz/Antonidas/q/2023-03-08-11-57-pm-rhStau

**Comment by antonyip** [comment]
Problem: `select * from "TERRA_DEV"."BRONZE"."BLOCKS" where  block_id = '2918084'`
Issue is-> bronze.blocks is height **2918084**, but the header :last_commit :height array is **2918083**.
  - Only the next block has the infomation of the current block

The validator address array is null because at the point of dbt_cloud executed, 2918084 is the latest block, thus block 2918085 does not exists and thus there is no information filled in for the VALIDATOR_ADDRESS_ARRAY.

A re-design of the silvers_blocks will be required to solve this problem.
